import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getSession, getSupabaseAuthClient } from '@/lib/auth/server';
import { buildMvaSummary } from '@/lib/accounting/exports/mva';
import { toCsv } from '@/lib/accounting/exports/csv';
import { renderPrintableHtml } from '@/lib/accounting/exports/pdf';
import { recordExport } from '@/lib/accounting/exports/history';
import { formatAmount } from '@/lib/accounting/frameworks';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const ALLOWED: ReadonlyArray<string> = ['super_admin', 'admin', 'accountant', 'auditor'];

const querySchema = z.object({
  from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  format: z.enum(['csv', 'pdf']).default('pdf'),
});

export async function GET(request: Request) {
  const session = await getSession();
  if (!session || !session.organizationId || !ALLOWED.includes(session.role)) {
    return NextResponse.json({ error: 'Forbidden.' }, { status: 403 });
  }
  const url = new URL(request.url);
  const today = new Date().toISOString().slice(0, 10);
  const yearStart = `${new Date().getFullYear()}-01-01`;
  const parsed = querySchema.safeParse({
    from: url.searchParams.get('from') ?? yearStart,
    to: url.searchParams.get('to') ?? today,
    format: url.searchParams.get('format') ?? 'pdf',
  });
  if (!parsed.success) {
    return NextResponse.json({ error: 'Invalid query.' }, { status: 400 });
  }

  const supabase = getSupabaseAuthClient();
  const { data: org } = await supabase
    .from('organizations')
    .select('default_country, name, registration_number, vat_number, base_currency')
    .eq('id', session.organizationId)
    .maybeSingle();
  if (org?.default_country !== 'NO') {
    return NextResponse.json(
      { error: 'MVA report is only available for Norway-jurisdiction organizations.' },
      { status: 422 },
    );
  }

  const summary = await buildMvaSummary(supabase, session.organizationId, {
    from: parsed.data.from,
    to: parsed.data.to,
  });

  const fileBase = `mva_${parsed.data.from}_${parsed.data.to}`;

  if (parsed.data.format === 'csv') {
    const headers = ['Category', 'Label', 'Rate %', 'Net amount', 'VAT amount'];
    const rows = summary.categories.map((c) => [
      c.category,
      c.label,
      c.rate_percent ?? '',
      c.net_amount,
      c.vat_amount,
    ]);
    rows.push(['totals', 'Output VAT', '', '', summary.totals.output_vat]);
    rows.push(['totals', 'Input VAT', '', '', summary.totals.input_vat]);
    rows.push(['totals', 'Payable to state', '', '', summary.totals.payable]);
    rows.push(['totals', 'Receivable from state', '', '', summary.totals.receivable]);
    const csv = toCsv(headers, rows);

    await recordExport({
      organizationId: session.organizationId,
      userId: session.userId,
      exportType: 'mva',
      jurisdiction: 'NO',
      periodFrom: parsed.data.from,
      periodTo: parsed.data.to,
      fileName: `${fileBase}.csv`,
    });

    return new NextResponse(csv, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="${fileBase}.csv"`,
        'Cache-Control': 'private, no-store',
      },
    });
  }

  // PDF path — printable HTML
  const html = renderPrintableHtml({
    title: 'MVA-melding — Norwegian VAT summary',
    subtitle: `Period ${parsed.data.from} → ${parsed.data.to} · ${org?.name ?? '—'} · Org. nr ${org?.registration_number ?? '—'}`,
    generatedAt: new Date().toISOString(),
    sections: [
      {
        heading: 'Per-category breakdown',
        columnHeaders: ['Category', 'Label', 'Rate %', 'Net amount', 'VAT amount'],
        rows: summary.categories.map((c) => [
          c.category,
          c.label,
          c.rate_percent !== null ? `${c.rate_percent.toFixed(2)}%` : '',
          formatAmount(c.net_amount, 'NO'),
          formatAmount(c.vat_amount, 'NO'),
        ]),
      },
      {
        heading: 'MVA-summering',
        columnHeaders: ['Metric', 'Value'],
        rows: [
          ['Sum utgående MVA (output)', formatAmount(summary.totals.output_vat, 'NO')],
          ['Sum inngående MVA (input)', formatAmount(summary.totals.input_vat, 'NO')],
          ['Skyldig MVA (payable to state)', formatAmount(summary.totals.payable, 'NO')],
          ['Tilgode MVA (receivable from state)', formatAmount(summary.totals.receivable, 'NO')],
        ],
      },
      {
        heading: 'Altinn submission notes',
        columnHeaders: ['Field', 'Value'],
        rows: [
          ['Organization', org?.name ?? ''],
          ['Org. nr', org?.registration_number ?? ''],
          ['MVA nr', org?.vat_number ?? ''],
          ['Reporting period', `${parsed.data.from} → ${parsed.data.to}`],
          ['Generated by', session.email],
        ],
      },
    ],
  });

  await recordExport({
    organizationId: session.organizationId,
    userId: session.userId,
    exportType: 'mva',
    jurisdiction: 'NO',
    periodFrom: parsed.data.from,
    periodTo: parsed.data.to,
    fileName: `${fileBase}.html`,
  });

  return new NextResponse(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="${fileBase}.html"`,
      'Cache-Control': 'private, no-store',
    },
  });
}
