import 'server-only';

import { getSupabaseAuthClient } from '@/lib/auth/server';
import { isFrameworkCode, FRAMEWORKS } from '@/lib/accounting/frameworks';

type Props = {
  organizationId: string;
  reportTitle: string;
  periodLabel?: string;
};

/**
 * Server-side print-only header + footer block. Shows nothing on
 * screen (`display:none` outside print), but stamps a regulator-ready
 * organization band at the top and a "Generated by FlyttGo …" footer
 * at the bottom of every printed page. The page also carries `data-
 * print-meta` so the global @page running-header pulls the same
 * jurisdiction line into the top-right slot of every continuation
 * page.
 *
 * Wrap the report body in a parent that has the .statutory-report-print
 * class so the @page string-set rules apply.
 */
export default async function StatutoryReportPrintMeta({
  organizationId,
  reportTitle,
  periodLabel,
}: Props) {
  const supabase = getSupabaseAuthClient();
  const { data: org } = await supabase
    .from('organizations')
    .select('name, default_country, base_currency, registration_number, vat_number, fiscal_year_start_month')
    .eq('id', organizationId)
    .maybeSingle();

  const framework = isFrameworkCode(org?.default_country) ? org!.default_country : 'NO';
  const cfg = FRAMEWORKS[framework];
  const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

  return (
    <>
      <div className="statutory-report-header">
        <div className="org-name">{org?.name ?? '—'}</div>
        <div className="org-meta">
          {[
            `Reg ${org?.registration_number ?? '—'}`,
            `VAT ${org?.vat_number ?? '—'}`,
            `Jurisdiction ${cfg.label}`,
            `Currency ${org?.base_currency ?? cfg.baseCurrency}`,
            `FY start month ${org?.fiscal_year_start_month ?? cfg.fiscalYearStartMonth}`,
            periodLabel ? `Period ${periodLabel}` : null,
          ]
            .filter(Boolean)
            .join(' · ')}
        </div>
      </div>

      <div data-print-meta className="hidden">
        {`${cfg.label} · ${org?.base_currency ?? cfg.baseCurrency} · ${reportTitle}`}
      </div>

      <div className="statutory-report-footer">
        Generated by FlyttGo Financial Control System
        <br />
        Jurisdiction {cfg.label} · Currency {org?.base_currency ?? cfg.baseCurrency} · Timestamp {generatedAt}
      </div>
    </>
  );
}
