/**
 * Regulator-compatibility footer metadata block.
 *
 * Every statutory export emitted by the workspace carries an identical
 * footer naming the generating system, the jurisdiction, the reporting
 * currency, and the UTC generation timestamp. The footer is the
 * compliance-audit trace that lets a regulator answer "what produced
 * this artefact?" without reaching into our application.
 *
 * Per format the footer renders as:
 *   CSV    A trailing comment row (`# field: value`) per attribute.
 *   Word   A `<p class="meta">` paragraph below the report body.
 *   PDF    A bordered `<div class="meta">` block at the foot of the
 *          rendered HTML.
 *   XML    A `<MetaData>` element appended to the document root, or
 *          embedded inside the SAF-T Header.SoftwareCompanyName /
 *          SoftwareID elements (already populated in saf-t.ts).
 */

export type FooterMeta = {
  jurisdiction: string;
  currency: string;
  generatedAt: string; // ISO 8601 UTC
  generatedBy: string; // user email or system identifier
  organizationName?: string;
  registrationNumber?: string | null;
  vatNumber?: string | null;
};

const FOOTER_LEAD = 'Generated by FlyttGo Financial Control System';

export function footerLines(meta: FooterMeta): string[] {
  return [
    FOOTER_LEAD,
    `Jurisdiction: ${meta.jurisdiction}`,
    `Currency: ${meta.currency}`,
    `Generated at: ${meta.generatedAt}`,
    `Generated by: ${meta.generatedBy}`,
    ...(meta.organizationName ? [`Organization: ${meta.organizationName}`] : []),
    ...(meta.registrationNumber ? [`Registration: ${meta.registrationNumber}`] : []),
    ...(meta.vatNumber ? [`VAT: ${meta.vatNumber}`] : []),
  ];
}

export function footerForCsv(meta: FooterMeta): string {
  return '\r\n' + footerLines(meta).map((l) => `# ${l}`).join('\r\n') + '\r\n';
}

export function footerForHtml(meta: FooterMeta): string {
  const lines = footerLines(meta)
    .map((l) => `<div>${escapeForHtml(l)}</div>`)
    .join('');
  return `<div class="regulator-footer" style="margin-top:24pt;padding-top:12pt;border-top:0.5pt solid #94A3B8;font-family:ui-monospace,JetBrains Mono,Menlo,monospace;font-size:8pt;color:#475569;letter-spacing:0.16em;text-transform:uppercase;line-height:1.6;page-break-inside:avoid;">${lines}</div>`;
}

export function footerForXml(meta: FooterMeta): string {
  const items = footerLines(meta).map((l) => `    <Meta>${escapeForXml(l)}</Meta>`).join('\n');
  return `\n  <RegulatorMetadata>\n${items}\n  </RegulatorMetadata>`;
}

function escapeForHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
function escapeForXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
