import 'server-only';

import type { SupabaseClient } from '@supabase/supabase-js';
import {
  buildBalanceSheet,
  buildGeneralLedger,
  buildIncomeStatement,
  buildTrialBalance,
} from '../reports';
import { toCsv } from './csv';

/**
 * US GAAP structured export bundle. Emits four CSV files keyed against
 * the IRS / accountant filing flows the accountant most often supports:
 *
 *   trial_balance.csv       — Schedule C / Form 1120 supporting workpaper
 *   general_ledger.csv      — Audit support, Form 1065 line-detail
 *   income_statement.csv    — Form 1120 / 1065 P&L attachments
 *   balance_sheet.csv       — Form 1120 Schedule L support
 *
 * The header rows in each CSV carry Form ID + Schedule + Period so the
 * file is self-describing when opened in isolation. Bundle assembly
 * returns a Map of { filename → csv } that the route handler walks
 * through and concatenates with multipart-style separators.
 */

type BundleArgs = {
  supabase: SupabaseClient;
  organizationId: string;
  range: { from: string; to: string };
  meta: {
    organization_name: string;
    ein: string | null;
    period_label: string;
  };
};

export type GaapBundle = Map<string, string>;

export async function buildGaapBundle({
  supabase,
  organizationId,
  range,
  meta,
}: BundleArgs): Promise<GaapBundle> {
  const out: GaapBundle = new Map();

  function metaHeader(filing: string, schedule: string): Array<Array<string | number>> {
    return [
      ['# US GAAP STRUCTURED EXPORT'],
      ['# Generated by FlyttGo Financial Control System'],
      [`# Organization: ${meta.organization_name}`],
      [`# EIN: ${meta.ein ?? '—'}`],
      [`# Filing: ${filing}`],
      [`# Schedule: ${schedule}`],
      [`# Period: ${meta.period_label}`],
      [`# From: ${range.from}`],
      [`# To: ${range.to}`],
      [],
    ];
  }

  // --- 1) trial_balance.csv ------------------------------------------
  const tb = await buildTrialBalance(supabase, organizationId, range);
  const tbHeader = ['Code', 'Account', 'Type', 'Debit', 'Credit', 'Balance'];
  const tbRows: Array<Array<string | number>> = [
    ...metaHeader('Form 1120 / 1065 / Schedule C', 'Trial Balance Workpaper'),
    tbHeader,
    ...tb.rows.map((r) => [r.code, r.name, r.account_type, r.debit, r.credit, r.balance]),
    ['', 'TOTAL', '', tb.totals.debit, tb.totals.credit, tb.totals.debit - tb.totals.credit],
  ];
  out.set('trial_balance.csv', toCsvWithRows(tbRows));

  // --- 2) general_ledger.csv -----------------------------------------
  const gl = await buildGeneralLedger(supabase, organizationId, range);
  const glRows: Array<Array<string | number>> = [
    ...metaHeader('Form 1120 / 1065 / Schedule C', 'General Ledger Support'),
    ['Entry', 'Date', 'Account code', 'Account name', 'Description', 'Side', 'Amount'],
    ...gl.map((r) => [
      r.entry_number,
      r.entry_date,
      r.account_code,
      r.account_name,
      r.description ?? '',
      r.side,
      r.amount,
    ]),
  ];
  out.set('general_ledger.csv', toCsvWithRows(glRows));

  // --- 3) income_statement.csv ---------------------------------------
  const is = await buildIncomeStatement(supabase, organizationId, range);
  const isRows: Array<Array<string | number>> = [
    ...metaHeader('Form 1120 line 1a–11 / Form 1065 line 1a–8', 'Income Statement'),
    ['Section', 'Code', 'Account', 'Amount'],
    ...is.revenue.lines.map((r) => ['Revenue', r.code, r.name, r.credit - r.debit]),
    ['Revenue', '', 'TOTAL REVENUE (Form 1120 Line 11)', is.revenue.total],
    ...is.cogs_and_expenses.lines.map((r) => ['Expenses', r.code, r.name, r.debit - r.credit]),
    ['Expenses', '', 'TOTAL EXPENSES', is.cogs_and_expenses.total],
    ['Result', '', 'NET INCOME (Form 1120 Line 28)', is.net_income],
  ];
  out.set('income_statement.csv', toCsvWithRows(isRows));

  // --- 4) balance_sheet.csv ------------------------------------------
  const bs = await buildBalanceSheet(supabase, organizationId, range.to);
  const bsRows: Array<Array<string | number>> = [
    ...metaHeader('Form 1120 Schedule L', `Balance Sheet — as of ${bs.as_of}`),
    ['Section', 'Code', 'Account', 'Amount'],
    ...bs.assets.lines.map((r) => ['Assets', r.code, r.name, r.debit - r.credit]),
    ['Assets', '', 'TOTAL ASSETS (Schedule L Line 15)', bs.assets.total],
    ...bs.liabilities.lines.map((r) => ['Liabilities', r.code, r.name, r.credit - r.debit]),
    ['Liabilities', '', 'TOTAL LIABILITIES (Schedule L Line 22)', bs.liabilities.total],
    ...bs.equity.lines.map((r) => ['Equity', r.code, r.name, r.credit - r.debit]),
    ['Equity', '', 'TOTAL EQUITY (Schedule L Line 27)', bs.equity.total],
    ['Check', '', 'TOTAL LIABILITIES + EQUITY', bs.total_liabilities_and_equity],
  ];
  out.set('balance_sheet.csv', toCsvWithRows(bsRows));

  return out;
}

function toCsvWithRows(rows: Array<Array<string | number>>): string {
  if (rows.length === 0) return '';
  const headers = rows[0].map((c) => String(c));
  return toCsv(headers, rows.slice(1));
}
