import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getSession, getSupabaseAuthClient } from '@/lib/auth/server';
import {
  buildBalanceSheet,
  buildIncomeStatement,
  buildTrialBalance,
} from '@/lib/accounting/reports';
import { toCsv } from '@/lib/accounting/exports/csv';
import { recordExport } from '@/lib/accounting/exports/history';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const ALLOWED: ReadonlyArray<string> = ['super_admin', 'admin', 'accountant', 'auditor'];

const querySchema = z.object({
  from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
});

/**
 * IFRS fallback reporting bundle.
 *
 * Generates the three core IFRS-classified statements:
 *   - Trial balance (account-by-account)
 *   - Statement of comprehensive income (P&L)
 *   - Statement of financial position (balance sheet)
 *
 * All amounts are in the organization's base currency. Lines posted
 * in foreign currency carry an exchange_rate snapshot in
 * journal_lines.exchange_rate; the generated amount_base_currency
 * column applies that snapshot, so historic figures don't shift when
 * future rates change.
 */

export async function GET(request: Request) {
  const session = await getSession();
  if (!session || !session.organizationId || !ALLOWED.includes(session.role)) {
    return NextResponse.json({ error: 'Forbidden.' }, { status: 403 });
  }
  const url = new URL(request.url);
  const today = new Date().toISOString().slice(0, 10);
  const yearStart = `${new Date().getFullYear()}-01-01`;
  const parsed = querySchema.safeParse({
    from: url.searchParams.get('from') ?? yearStart,
    to: url.searchParams.get('to') ?? today,
  });
  if (!parsed.success) {
    return NextResponse.json({ error: 'Invalid query.' }, { status: 400 });
  }

  const supabase = getSupabaseAuthClient();
  const { data: org } = await supabase
    .from('organizations')
    .select('default_country, name, base_currency, registration_number')
    .eq('id', session.organizationId)
    .maybeSingle();
  if (org?.default_country !== 'IFRS') {
    return NextResponse.json(
      { error: 'IFRS bundle is only available for IFRS-jurisdiction organizations.' },
      { status: 422 },
    );
  }

  const range = { from: parsed.data.from, to: parsed.data.to };
  const tb = await buildTrialBalance(supabase, session.organizationId, range);
  const is = await buildIncomeStatement(supabase, session.organizationId, range);
  const bs = await buildBalanceSheet(supabase, session.organizationId, parsed.data.to);

  const metaRows: Array<Array<string | number>> = [
    ['# IFRS REPORTING PACKAGE'],
    ['# Generated by FlyttGo Financial Control System'],
    [`# Organization: ${org.name}`],
    [`# Registration: ${org.registration_number ?? '—'}`],
    [`# Reporting currency: ${org.base_currency}`],
    [`# Period: ${parsed.data.from} → ${parsed.data.to}`],
    ['# Currency notes: foreign-currency lines converted at the'],
    ['# exchange_rate snapshot active at posting date.'],
    [],
  ];

  const segments: string[] = [];

  segments.push(
    toCsv(
      ['Section', 'Code', 'Account', 'Type', 'Debit', 'Credit', 'Balance'],
      [
        ...metaRows,
        ['Header', '', 'TRIAL BALANCE', '', '', '', ''],
        ...tb.rows.map((r) => ['', r.code, r.name, r.account_type, r.debit, r.credit, r.balance]),
        ['', '', 'TOTAL', '', tb.totals.debit, tb.totals.credit, tb.totals.debit - tb.totals.credit],
      ],
    ),
  );

  segments.push(
    toCsv(
      ['Section', 'Code', 'Account', 'Amount'],
      [
        ['Header', '', 'STATEMENT OF COMPREHENSIVE INCOME', ''],
        ...is.revenue.lines.map((r) => ['Revenue', r.code, r.name, r.credit - r.debit]),
        ['Revenue', '', 'TOTAL REVENUE', is.revenue.total],
        ...is.cogs_and_expenses.lines.map((r) => ['Expenses', r.code, r.name, r.debit - r.credit]),
        ['Expenses', '', 'TOTAL EXPENSES', is.cogs_and_expenses.total],
        ['Result', '', 'PROFIT FOR THE PERIOD', is.net_income],
      ],
    ),
  );

  segments.push(
    toCsv(
      ['Section', 'Code', 'Account', 'Amount'],
      [
        ['Header', '', `STATEMENT OF FINANCIAL POSITION — as at ${bs.as_of}`, ''],
        ...bs.assets.lines.map((r) => ['Assets', r.code, r.name, r.debit - r.credit]),
        ['Assets', '', 'TOTAL ASSETS', bs.assets.total],
        ...bs.liabilities.lines.map((r) => ['Liabilities', r.code, r.name, r.credit - r.debit]),
        ['Liabilities', '', 'TOTAL LIABILITIES', bs.liabilities.total],
        ...bs.equity.lines.map((r) => ['Equity', r.code, r.name, r.credit - r.debit]),
        ['Equity', '', 'TOTAL EQUITY', bs.equity.total],
        ['Check', '', 'TOTAL EQUITY + LIABILITIES', bs.total_liabilities_and_equity],
      ],
    ),
  );

  const combined = segments
    .map((s, i) => `\r\n# ===== ${['trial_balance', 'income_statement', 'balance_sheet'][i]}.csv =====\r\n${s}`)
    .join('\r\n');

  await recordExport({
    organizationId: session.organizationId,
    userId: session.userId,
    exportType: 'ifrs-package',
    jurisdiction: 'IFRS',
    periodFrom: parsed.data.from,
    periodTo: parsed.data.to,
    fileName: `ifrs_package_${parsed.data.from}_${parsed.data.to}.csv`,
  });

  return new NextResponse(combined, {
    status: 200,
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="ifrs_package_${parsed.data.from}_${parsed.data.to}.csv"`,
      'Cache-Control': 'private, no-store',
    },
  });
}
