/**
 * Workspace-specific string table.
 *
 * The marketing site has its own deep i18n tree under
 * src/lib/i18n/dictionaries.ts. The accounting workspace uses this
 * separate, smaller table because most of its surface is technical
 * (account codes, journal numbers, mono labels) and doesn't translate
 * — only the headings, primary actions and statutory-export labels
 * benefit from a Norwegian rendering.
 *
 * The brief calls out support for English + Norwegian today, with a
 * structure that can extend to UK English / US English later. UK and
 * US dialects share the canonical `en` key and override only when a
 * spelling actually diverges (organisation vs organization etc.).
 */

export const WORKSPACE_LANGS = ['en', 'no', 'en-GB', 'en-US'] as const;
export type WorkspaceLang = (typeof WORKSPACE_LANGS)[number];

export const WORKSPACE_LANG_LABEL: Record<WorkspaceLang, string> = {
  en: 'English',
  no: 'Norsk (bokmål)',
  'en-GB': 'English (UK)',
  'en-US': 'English (US)',
};

export const WORKSPACE_STRINGS = {
  en: {
    sign_in_title: 'Sign in to the financial workspace.',
    sign_in_subtitle:
      'Accountants, auditors and platform administrators only. Sessions are scoped to the organization on the account record.',
    sign_in_button: 'Sign in',
    workspace_journal: 'Journal',
    workspace_chart: 'Chart of accounts',
    workspace_vat: 'VAT center',
    workspace_reports: 'Reports',
    workspace_exports: 'Statutory exports',
    workspace_profile: 'Organization profile',
    workspace_settings: 'Settings',
    statutory_disclaimer:
      'Generated by FlyttGo Financial Control System. Statutory exports require accounting-firm review before submission.',
  },
  no: {
    sign_in_title: 'Logg inn på finansarbeidsflaten.',
    sign_in_subtitle:
      'Kun for regnskapsførere, revisorer og plattformadministratorer. Sesjoner er begrenset til organisasjonen som er knyttet til kontoen.',
    sign_in_button: 'Logg inn',
    workspace_journal: 'Bilagsregister',
    workspace_chart: 'Kontoplan',
    workspace_vat: 'MVA-senter',
    workspace_reports: 'Rapporter',
    workspace_exports: 'Lovpålagte eksporter',
    workspace_profile: 'Organisasjonsprofil',
    workspace_settings: 'Innstillinger',
    statutory_disclaimer:
      'Generert av FlyttGo Financial Control System. Lovpålagte eksporter må gjennomgås av regnskapsbyrå før innlevering.',
  },
  'en-GB': {
    sign_in_title: 'Sign in to the financial workspace.',
    sign_in_subtitle:
      'Accountants, auditors and platform administrators only. Sessions are scoped to the organisation on the account record.',
    sign_in_button: 'Sign in',
    workspace_journal: 'Journal',
    workspace_chart: 'Chart of accounts',
    workspace_vat: 'VAT centre',
    workspace_reports: 'Reports',
    workspace_exports: 'Statutory exports',
    workspace_profile: 'Organisation profile',
    workspace_settings: 'Settings',
    statutory_disclaimer:
      'Generated by FlyttGo Financial Control System. Statutory exports require accountancy-firm review before submission.',
  },
  'en-US': {
    sign_in_title: 'Sign in to the financial workspace.',
    sign_in_subtitle:
      'Accountants, auditors and platform administrators only. Sessions are scoped to the organization on the account record.',
    sign_in_button: 'Sign in',
    workspace_journal: 'Journal',
    workspace_chart: 'Chart of accounts',
    workspace_vat: 'Sales-tax center',
    workspace_reports: 'Reports',
    workspace_exports: 'Statutory exports',
    workspace_profile: 'Organization profile',
    workspace_settings: 'Settings',
    statutory_disclaimer:
      'Generated by FlyttGo Financial Control System. Statutory exports require CPA review before submission.',
  },
} as const satisfies Record<WorkspaceLang, Record<string, string>>;

export type WorkspaceStringKey = keyof typeof WORKSPACE_STRINGS.en;

export function isWorkspaceLang(value: unknown): value is WorkspaceLang {
  return typeof value === 'string' && (WORKSPACE_LANGS as readonly string[]).includes(value);
}

export function t(lang: WorkspaceLang, key: WorkspaceStringKey): string {
  return WORKSPACE_STRINGS[lang][key] ?? WORKSPACE_STRINGS.en[key];
}
